/* Generated by scripts/fetch-media.mjs — do not edit by hand.
 *
 * Every photograph on this site is a real photograph of a real place, reused
 * from Wikimedia Commons under the licence recorded beside it. `where` is the
 * place in the frame, which is not always the village of the farm the picture
 * illustrates: the demo farms are invented, their landscapes are not, and the
 * credit under each picture says so rather than letting the page imply
 * otherwise. Run `npm run media:fetch` to regenerate. */

import type { I18nJson } from './types';

export interface Photo {
  id: string;
  /** Widest encoded file; also the <img src> for browsers without srcset. */
  src: string;
  /** AVIF ladder, newest format first, for the <source> element. */
  avif: string;
  /** 20px WebP, inlined, shown until the real file decodes. */
  blur: string;
  width: number;
  height: number;
  alt: I18nJson;
  where: I18nJson;
  author: string;
  licence: string;
  licenceUrl: string;
  source: string;
}

export const PHOTOS: Record<string, Photo> = {
  "hedvi-sunset": {
    id: "hedvi-sunset",
    src: "/photos/hedvi-sunset-1280.jpg",
    avif: "/photos/hedvi-sunset-640.avif 640w, /photos/hedvi-sunset-1280.avif 1280w, /photos/hedvi-sunset-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APxl8s1GsqCSisAgBkCMJQBOgA2//+50j+Ry/AAD6Zu02Tdbj2uQPVp9usT5Jy7fNGKeuFyMtPO3o2Er5Nq1zjItBD4MqqAAA",
    width: 1280, height: 720,
    alt: {"en":"The sun going down over the sea at Hedvi on the Konkan coast","hi":"कोंकण तट पर हेदवी में समुद्र के ऊपर डूबता सूरज","mr":"कोकण किनाऱ्यावर हेदवीत समुद्रावर मावळणारा सूर्य"},
    where: {"en":"Hedvi, Ratnagiri","hi":"हेदवी, रत्नागिरी","mr":"हेदवी, रत्नागिरी"},
    author: "urbzoo",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Konkan_-_Hedvi_Village_-_Part_4_20151222_(23918313471).jpg",
  },
  "aare-ware": {
    id: "aare-ware",
    src: "/photos/aare-ware-1280.jpg",
    avif: "/photos/aare-ware-640.avif 640w, /photos/aare-ware-1280.avif 1280w, /photos/aare-ware-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoUAA0APxl2slCspySisAgBkCMJaACdABbTe5v4/3QAAP66adlLtwR536FEm502mgGvgOt3dUKlNAFaGhYkfkOXtw+a8Lzc4LFq+OmvKjAxFVJ6ejeaAAAA",
    width: 1280, height: 720,
    alt: {"en":"The turquoise cove at Aare Ware, palms coming down to the sand","hi":"आरे वारे की फ़िरोज़ी खाड़ी, रेत तक उतरते नारियल","mr":"आरे वारेची निळीशार खाडी, वाळूपर्यंत उतरलेली माडं"},
    where: {"en":"Aare Ware, Ratnagiri","hi":"आरे वारे, रत्नागिरी","mr":"आरे वारे, रत्नागिरी"},
    author: "Amankr3081",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Aare_Ware_Beach.jpg",
  },
  "mhapan-coast": {
    id: "mhapan-coast",
    src: "/photos/mhapan-coast-1280.jpg",
    avif: "/photos/mhapan-coast-640.avif 640w, /photos/mhapan-coast-1280.avif 1280w, /photos/mhapan-coast-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAA0APxl2slEspySisAgBkCMJZAC/OBwrxP3hACw5ubAA/lRmdQ7QCmUoC5lNbUrxL21f58uuMO5T6/UGRNwTdsRkSS01i0xP1zaUwSYqAAAA",
    width: 1280, height: 720,
    alt: {"en":"Surf breaking over the rocks on the Sindhudurg shore","hi":"सिंधुदुर्ग के किनारे चट्टानों पर टूटती लहरें","mr":"सिंधुदुर्गच्या किनाऱ्यावर खडकांवर फुटणाऱ्या लाटा"},
    where: {"en":"Mhapan, Sindhudurg","hi":"म्हापण, सिंधुदुर्ग","mr":"म्हापण, सिंधुदुर्ग"},
    author: "URVASHI RAO",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coast_line_of_mhapan_maharashtra.jpg",
  },
  "rice-terraces": {
    id: "rice-terraces",
    src: "/photos/rice-terraces-1280.jpg",
    avif: "/photos/rice-terraces-640.avif 640w, /photos/rice-terraces-1280.avif 1280w, /photos/rice-terraces-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoUAA0APxl2slEspySisAgBkCMJaAAAW7A8vz7STmBAAP3bnJRScKra/H4lxPA+D7GvZbl3KRfE/5wv+Tr/8AiX0CiQObgm2cd6Qi69C/dmOha3q2wAAA==",
    width: 1280, height: 720,
    alt: {"en":"Terraced paddy below tiled roofs in a Ratnagiri village","hi":"रत्नागिरी के गाँव में खपरैल छतों के नीचे सीढ़ीनुमा भात-शेत","mr":"रत्नागिरीच्या गावात कौलारू छपरांखाली भातशेतीच्या पायऱ्या"},
    where: {"en":"Ratnagiri district","hi":"रत्नागिरी ज़िला","mr":"रत्नागिरी जिल्हा"},
    author: "Rutujaslkr",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Rice_Plantation.jpg",
  },
  "pabhare-house": {
    id: "pabhare-house",
    src: "/photos/pabhare-house-1280.jpg",
    avif: "/photos/pabhare-house-640.avif 640w, /photos/pabhare-house-1280.avif 1280w, /photos/pabhare-house-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAA0APxl2slEspySisAgBkCMJYgCADCcgdPomO9AnCL4AAP7hne02dZV6u8rn2lUIO7AVCKEaOsAnpy+XrezPumKTJprjxVJCWJqXCXbbm5B5uixrUJ1+On07jmv4CLgAAA==",
    width: 1280, height: 720,
    alt: {"en":"A laterite house at the edge of its own paddy, coconut behind it","hi":"अपनी ही भात-शेत के किनारे जांभा पत्थर का घर, पीछे नारियल","mr":"स्वतःच्याच भातशेताच्या कडेला जांभ्या दगडाचं घर, मागे माडं"},
    where: {"en":"Pabhare, Ratnagiri","hi":"पाभरे, रत्नागिरी","mr":"पाभरे, रत्नागिरी"},
    author: "Rutujaslkr",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Local_house_Pabhare.jpg",
  },
  "zarye-mist": {
    id: "zarye-mist",
    src: "/photos/zarye-mist-1280.jpg",
    avif: "/photos/zarye-mist-640.avif 640w, /photos/zarye-mist-1280.avif 1280w, /photos/zarye-mist-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUAA0APxl6slCsqCSisAgBkCMJZwC7ACHZg9hBW2EfAAD+3rcO2Jr5DOWNHcVM6N4Dd9/Ml+9vPLMg6AAAAA==",
    width: 1280, height: 720,
    alt: {"en":"Cloud sitting on the forested hills above Zarye","hi":"ज़ार्ये के ऊपर जंगली पहाड़ियों पर बैठा बादल","mr":"झर्येवरच्या जंगली डोंगरांवर बसलेले ढग"},
    where: {"en":"Zarye, Ratnagiri","hi":"ज़ार्ये, रत्नागिरी","mr":"झर्ये, रत्नागिरी"},
    author: "Savita Sawant",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atmosphere_Zarye.jpg",
  },
  "mango-laterite": {
    id: "mango-laterite",
    src: "/photos/mango-laterite-1280.jpg",
    avif: "/photos/mango-laterite-640.avif 640w, /photos/mango-laterite-1280.avif 1280w, /photos/mango-laterite-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAA0APxl0slCspqSisAgBkCMJaACsABbTe5vv1RgA/q+bPFiOqAGu0l0YYKNesFLM/vCXi9qQFk3ATKLhR8zoz4qx2gwNwH68FH3ZUV56D9LlVMhnAAAA",
    width: 1280, height: 720,
    alt: {"en":"Mango trees spaced across a laterite plateau after the rains","hi":"बारिश के बाद जांभा पठार पर दूर-दूर लगे आम के पेड़","mr":"पावसानंतर जांभ्या पठारावर अंतरा-अंतरावर उभी आंब्याची झाडं"},
    where: {"en":"Ratnagiri district","hi":"रत्नागिरी ज़िला","mr":"रत्नागिरी जिल्हा"},
    author: "Rohitjahnavi",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_orchard_in_lateritic_plateau.jpg",
  },
  "mango-laterite-2": {
    id: "mango-laterite-2",
    src: "/photos/mango-laterite-2-960.jpg",
    avif: "/photos/mango-laterite-2-480.avif 480w, /photos/mango-laterite-2-960.avif 960w",
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA0APxl2slEspySisAgBkCMJagC1CBgC/pWbEr7njoswAP6uxg43809iXfB6iLy46jjvp+96drAp0R4ZkFyd4cOGUHRbJgCI2lhrz4EJKXOYyFsGxu7JJNmKHz6gRXZyChi0w55AAA==",
    width: 960, height: 600,
    alt: {"en":"The edge of a mango wadi where the laterite breaks open","hi":"आम की वाड़ी का छोर, जहाँ जांभा पत्थर खुल जाता है","mr":"आंब्याच्या वाडीचा कडा, जिथे जांभा दगड उघडा पडतो"},
    where: {"en":"Ratnagiri district","hi":"रत्नागिरी ज़िला","mr":"रत्नागिरी जिल्हा"},
    author: "Rohitjahnavi",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_orchard_in_lateritic_plateau_2.jpg",
  },
  "vengurla-cashew": {
    id: "vengurla-cashew",
    src: "/photos/vengurla-cashew-960.jpg",
    avif: "/photos/vengurla-cashew-480.avif 480w, /photos/vengurla-cashew-960.avif 960w",
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoUAA0APxl0slCspqSisAgBkCMJagC06BXzgpe0MJZmIAD+0D88jW6gjT0NVaViw8OnWHGhUUoIZaUF/rGJ5m+NX9Hrv7uDsmYl0l0MoaENb9G6rAaBnPFbTUVqp7A4jsBlbiccd4BrPO77Ta073Rw1YIsSQAAA",
    width: 960, height: 600,
    alt: {"en":"Unripe Vengurla cashews still on the branch","hi":"डाली पर लगे कच्चे वेंगुर्ला काजू","mr":"फांदीवरचे कच्चे वेंगुर्ला काजू"},
    where: {"en":"Vengurla, Sindhudurg","hi":"वेंगुर्ला, सिंधुदुर्ग","mr":"वेंगुर्ला, सिंधुदुर्ग"},
    author: "Sandeep Vengurlekar",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Bunch_of_unripe_Vengurla_cashews.jpg",
  },
  "vengurla-road": {
    id: "vengurla-road",
    src: "/photos/vengurla-road-960.jpg",
    avif: "/photos/vengurla-road-480.avif 480w, /photos/vengurla-road-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUAA0APxl4slEspySisAgBkCMJZQAAW+tcXFvdtyegAP7uj4dSaSIruhaIcNSYk0v4Sn1Vw2Q2GNGa+Mwjw3dXZBfRycFFrh1Ljp8AAAA=",
    width: 960, height: 600,
    alt: {"en":"The Vengurla–Shiroda road closing over into a tunnel of trees","hi":"वेंगुर्ला–शिरोडा सड़क, पेड़ों की सुरंग बनती हुई","mr":"वेंगुर्ला–शिरोडा रस्ता, झाडांची कमान होत जाणारा"},
    where: {"en":"Vengurla–Shiroda, Sindhudurg","hi":"वेंगुर्ला–शिरोडा, सिंधुदुर्ग","mr":"वेंगुर्ला–शिरोडा, सिंधुदुर्ग"},
    author: "Alexey Komarov",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Vengurla_-_Shiroda_Road_,Maharashtra,_India.jpg",
  },
  "konkan-coconut": {
    id: "konkan-coconut",
    src: "/photos/konkan-coconut-960.jpg",
    avif: "/photos/konkan-coconut-480.avif 480w, /photos/konkan-coconut-960.avif 960w",
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQAwCdASoUAA0APxl2slCspySisAgBkCMJYwC7ABiDZDVsxrqAAP7nQUMN+3I5z+SyD5GG7say8ZLk6hDrjAl2sUG6O6NWlk6lyU9GTwRDgLf+Z56ZHNZAkKEDG8GNwnUAXgLyxWeqZWiAAAA=",
    width: 960, height: 600,
    alt: {"en":"Coconut palms leaning out over the sand on the Konkan shore","hi":"कोंकण के किनारे रेत पर झुके नारियल के पेड़","mr":"कोकणच्या किनाऱ्यावर वाळूवर झुकलेली माडं"},
    where: {"en":"Konkan coast","hi":"कोंकण तट","mr":"कोकण किनारा"},
    author: "Marathi mulgaa",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Bent_Coconut_Tree_in_Konkan_India.JPG",
  },
  "palm-paddy": {
    id: "palm-paddy",
    src: "/photos/palm-paddy-960.jpg",
    avif: "/photos/palm-paddy-480.avif 480w, /photos/palm-paddy-960.avif 960w",
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoUAA0APxl2slCspySisAgBkCMJQAAL5dX3RMROK1DrgDYYAAD+2oRFc+4MMGlBc7k/16s2B2aPSxk5WIXiVwFNRJFuwJcL9B7b7frGv9nnTZfeLfb67F1BMMpbd4oopbBiGV4MQ2UiC4AA",
    width: 960, height: 600,
    alt: {"en":"Tall palms standing in a flooded green paddy","hi":"भरी हुई हरी भात-शेत में खड़े ऊँचे ताड़","mr":"भरलेल्या हिरव्या भातशेतात उभी उंच माडं"},
    where: {"en":"Coastal Maharashtra","hi":"तटीय महाराष्ट्र","mr":"किनारपट्टीचा महाराष्ट्र"},
    author: "Dimple Bheemani",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Nature_green.jpg",
  },
  "jawhar-falls": {
    id: "jawhar-falls",
    src: "/photos/jawhar-falls-1280.jpg",
    avif: "/photos/jawhar-falls-640.avif 640w, /photos/jawhar-falls-1280.avif 1280w, /photos/jawhar-falls-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoUAA0APxl2slEspySisAgBkCMJaADG9B6nVrBQ70tYAPfby4rbHscNOgaZX7BhVmpGavE5Dr0fwKZ2/8LNX4BRjq6pVWwBnNBqTZAzKIAAAA==",
    width: 1280, height: 720,
    alt: {"en":"The Hiradpada fall dropping into green below Jawhar","hi":"जव्हार के नीचे हरियाली में गिरता हिरडपाड़ा झरना","mr":"जव्हारच्या खाली हिरवाईत कोसळणारा हिरडपाडा धबधबा"},
    where: {"en":"Hiradpada, Jawhar, Palghar","hi":"हिरडपाड़ा, जव्हार, पालघर","mr":"हिरडपाडा, जव्हार, पालघर"},
    author: "Star Dust H",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hiradpada_Waterfall,_Jawhar.jpg",
  },
  "chandgad-hills": {
    id: "chandgad-hills",
    src: "/photos/chandgad-hills-960.jpg",
    avif: "/photos/chandgad-hills-480.avif 480w, /photos/chandgad-hills-960.avif 960w",
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAA0APxl2slEspySisAgBkCMJYwAAXBdVnqyYkj2DaAD94jklBLBrP5Wojk/fbvGfOKOHW+34qSECbAug8AAA",
    width: 960, height: 600,
    alt: {"en":"Steep forested Sahyadri slopes with water coming down them","hi":"खड़ी जंगली सह्याद्री ढलानें, उन पर उतरता पानी","mr":"उभे जंगली सह्याद्री उतार, त्यावरून उतरणारे पाणी"},
    where: {"en":"Chandgad, Western Ghats","hi":"चंदगड, पश्चिमी घाट","mr":"चंदगड, सह्याद्री"},
    author: "Aniket7",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Chandgad_Hill%27s_04.jpg",
  },
  "green-lush": {
    id: "green-lush",
    src: "/photos/green-lush-960.jpg",
    avif: "/photos/green-lush-480.avif 480w, /photos/green-lush-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBACdASoUAA0APxl2s1EspySisAgBkCMJYgCw7B4IMVV3mdfFZLUCAAD9/TCI69hh0xAThgtp1zl3aFm3FaTus3KuEMEGboE7khtjVnWCM2Lk8aq0m466vW2QTeqGQAA=",
    width: 960, height: 600,
    alt: {"en":"A fall, a lake and green hills folded in behind them","hi":"झरना, झील, और पीछे मुड़ती हरी पहाड़ियाँ","mr":"धबधबा, तलाव, आणि मागे दुमडलेले हिरवे डोंगर"},
    where: {"en":"Western Ghats, Maharashtra","hi":"पश्चिमी घाट, महाराष्ट्र","mr":"सह्याद्री, महाराष्ट्र"},
    author: "Gargi Gore",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_Lush.jpg",
  },
  "sula-vineyard": {
    id: "sula-vineyard",
    src: "/photos/sula-vineyard-1280.jpg",
    avif: "/photos/sula-vineyard-640.avif 640w, /photos/sula-vineyard-1280.avif 1280w, /photos/sula-vineyard-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAA0APxl0slCspqSisAgBkCMJZgBVI4btv3iTzBsgAP7ToPFNgKkbQIei7RuqCeAyY+nNLu6FTKh8rJxyxn5HQ9DEDqgAAAA=",
    width: 1280, height: 720,
    alt: {"en":"Rows of vines running out towards the Nashik hills","hi":"नासिक की पहाड़ियों की ओर जाती अंगूर की कतारें","mr":"नाशिकच्या डोंगरांकडे जाणाऱ्या द्राक्षवेलींच्या रांगा"},
    where: {"en":"Nashik","hi":"नासिक","mr":"नाशिक"},
    author: "Wikieditor11221",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sula_Grape_Vineyard.jpg",
  },
  "sula-estate": {
    id: "sula-estate",
    src: "/photos/sula-estate-960.jpg",
    avif: "/photos/sula-estate-480.avif 480w, /photos/sula-estate-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA0APxl2slEspySisAgBkCMJaACdAB6qDZuc0+vlgADN8N4KMTouba61o/dUITuC4eWmL8jGwCEN78K7TQZ0Dazjx4/1Wny12AgOzEjpH+alMZvVYIGGAAA=",
    width: 960, height: 600,
    alt: {"en":"A Nashik vineyard estate seen from above the vines","hi":"बेलों के ऊपर से दिखता नासिक का अंगूर-बाग़","mr":"वेलींच्या वरून दिसणारा नाशिकचा द्राक्षमळा"},
    where: {"en":"Nashik","hi":"नासिक","mr":"नाशिक"},
    author: "Puneets26",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sula_Vineyards_Updated_View.jpg",
  },
  "bhavli-igatpuri": {
    id: "bhavli-igatpuri",
    src: "/photos/bhavli-igatpuri-1280.jpg",
    avif: "/photos/bhavli-igatpuri-640.avif 640w, /photos/bhavli-igatpuri-1280.avif 1280w, /photos/bhavli-igatpuri-1920.avif 1920w",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAA0APxl0sVCspqSisAgBkCMJQBOkCYhl/VjHNNRvfy/oAN5hZzmMrrei2q0/41yJ2EHONLX8iNDPB89YJjyZY8n1a9guWHH+x114OrSZU2zb+hTBXBAA",
    width: 1280, height: 720,
    alt: {"en":"The Bhavli water held between green hills at Igatpuri","hi":"इगतपुरी में हरी पहाड़ियों के बीच भावली का पानी","mr":"इगतपुरीत हिरव्या डोंगरांमध्ये अडवलेलं भावलीचं पाणी"},
    where: {"en":"Igatpuri, Nashik","hi":"इगतपुरी, नासिक","mr":"इगतपुरी, नाशिक"},
    author: "Shreekanth Ramasamy",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Bhavli_Reservoir_in_Igatpuri_Hill_sttation.jpg",
  },
  "koroli-valley": {
    id: "koroli-valley",
    src: "/photos/koroli-valley-960.jpg",
    avif: "/photos/koroli-valley-480.avif 480w, /photos/koroli-valley-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoUAA0APxl2slCspySisAgBkCMJaACsACHZeFbGMaQAAP7qeQ7sRaZTeB7Y+cWLIxYD9HipzcQHPYdT55VbB0T7YLmmyJvtlGinCHcgb6jGDww3AAA=",
    width: 960, height: 600,
    alt: {"en":"A river turning through green fields under the Nashik hills","hi":"नासिक की पहाड़ियों तले हरे खेतों से मुड़ती नदी","mr":"नाशिकच्या डोंगरांखाली हिरव्या शेतांतून वळणारी नदी"},
    where: {"en":"Koroli, Nashik district","hi":"कोरोली, नासिक ज़िला","mr":"कोरोली, नाशिक जिल्हा"},
    author: "Gradtamu",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Koroli-Hill-Station-Scenic-View.jpg",
  },
  "satpura-lohara": {
    id: "satpura-lohara",
    src: "/photos/satpura-lohara-960.jpg",
    avif: "/photos/satpura-lohara-480.avif 480w, /photos/satpura-lohara-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAA0APxl2slCspySisAgBkCMJZgCdACHJJpuo2wAA/ucYQqu/2lPe4X6jEZg5WfE0JuxnDUfp5ssEDwVUklleleBjasETBhnR3b958cYSwEs1wjpnAAAA",
    width: 960, height: 600,
    alt: {"en":"The dry shoulders of the Satpura range above the fields","hi":"खेतों के ऊपर सतपुड़ा के सूखे कंधे","mr":"शेतांच्या वर सातपुड्याचे कोरडे खांदे"},
    where: {"en":"Lohara, Satpura range","hi":"लोहारा, सतपुड़ा","mr":"लोहारा, सातपुडा"},
    author: "ABHIJEET",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Satpura_range_at_Lohara.jpg",
  },
  "onion-harvest": {
    id: "onion-harvest",
    src: "/photos/onion-harvest-960.jpg",
    avif: "/photos/onion-harvest-480.avif 480w, /photos/onion-harvest-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAA0APxl0slCspqSisAgBkCMJbACdAB9g/R7q+T/DMADfuPojuoB0To0UZIaGX9s1Oq+iBJs+kN3pPERLfnICWfFcOPX+N4jmgDyXjGgAAA==",
    width: 960, height: 600,
    alt: {"en":"A long windrow of just-lifted red onions drying in the field","hi":"खेत में सूखती अभी-अभी निकाली लाल प्याज़ की लंबी कतार","mr":"शेतात वाळत घातलेल्या नुकत्याच काढलेल्या लाल कांद्याची लांब रांग"},
    where: {"en":"Maharashtra","hi":"महाराष्ट्र","mr":"महाराष्ट्र"},
    author: "Gajanan Jagannath Jagdale",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Onion_farming.jpg",
  },
  "targaon-farmland": {
    id: "targaon-farmland",
    src: "/photos/targaon-farmland-960.jpg",
    avif: "/photos/targaon-farmland-480.avif 480w, /photos/targaon-farmland-960.avif 960w",
    blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoUAA0APxl2s1EspySisAgBkCMJagCdMoLT+z/4DsvjWxvKCtmkAP7nNC70FdLUgPHa8ki1nbPzDqTkvsGWL2pusdkITyiERRjq4DrCclspwLSGJ6RJEUxk/AAAAA==",
    width: 960, height: 600,
    alt: {"en":"Worked red earth running out to the horizon at Targaon","hi":"तरगाँव में क्षितिज तक जाती जुती लाल मिट्टी","mr":"तरगावात क्षितिजापर्यंत गेलेली नांगरलेली लाल माती"},
    where: {"en":"Targaon, Maharashtra","hi":"तरगाँव, महाराष्ट्र","mr":"तरगाव, महाराष्ट्र"},
    author: "Contributers2020",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Farmland_in_the_village_of_Targaon,_Maharashtra_3.jpg",
  },
  "sugarcane-village": {
    id: "sugarcane-village",
    src: "/photos/sugarcane-village-960.jpg",
    avif: "/photos/sugarcane-village-480.avif 480w, /photos/sugarcane-village-960.avif 960w",
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUAA0APxl0sVCspqSisAgBkCMJQBOgBECk9qctwNf+6gD8+9Xy9rzIwzXattX3Fac9ia3IXf2M5RO1y5VjlD6kdPxCNUTC+vR1d5Jv+Rlr2vdOHT746nuwFF63o0WFQZJDPQAA",
    width: 960, height: 600,
    alt: {"en":"Farmers working the edge of a cane field","hi":"गन्ने के खेत के किनारे काम करते किसान","mr":"उसाच्या शेताच्या कडेला काम करणारे शेतकरी"},
    where: {"en":"Maharashtra","hi":"महाराष्ट्र","mr":"महाराष्ट्र"},
    author: "Omar AV",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Village_life_,_Farmers_on_Sugar_cane_field_-_panoramio.jpg",
  },
  "paddy-harvest": {
    id: "paddy-harvest",
    src: "/photos/paddy-harvest-960.jpg",
    avif: "/photos/paddy-harvest-480.avif 480w, /photos/paddy-harvest-960.avif 960w",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA0APxl0slCspqSisAgBkCMJYgCdACKygqm2QAH+MAD+W+rx2HfEmRaGcvfDpgVlf2wpTjnQDXU4df22dVHTK12PcHsoaho+L9VQo7wljjG2PQVMhW7gAAA=",
    width: 960, height: 600,
    alt: {"en":"Cut paddy lying in the field at harvest","hi":"कटाई के समय खेत में पड़ा कटा हुआ धान","mr":"कापणीच्या वेळी शेतात पडलेलं कापलेलं भात"},
    where: {"en":"India","hi":"भारत","mr":"भारत"},
    author: "Drashokk",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Harvesting_Paddy_01.jpg",
  },
  "banana-grove": {
    id: "banana-grove",
    src: "/photos/banana-grove-960.jpg",
    avif: "/photos/banana-grove-480.avif 480w, /photos/banana-grove-960.avif 960w",
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAA0APxl2slEspySisAgBkCMJaACdABSr/yq0Gmi6sAAA/r+e+Lfs31+bOosKcT+RXT7HcwxF7k73Me+gQbLdMNOXyxWdZtaRq/6lAeYdSNFGtSnh39lotM36IyOYJQwme0Ngn99Qy9Mk/EMAAA==",
    width: 960, height: 600,
    alt: {"en":"A close stand of banana, leaf over leaf","hi":"पास-पास खड़े केले, पत्ते पर पत्ता","mr":"दाटीवाटीने उभी केळी, पानावर पान"},
    where: {"en":"India","hi":"भारत","mr":"भारत"},
    author: "Valtino44",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:BANANA_PLANTATION.jpg",
  },
  "banana-yard": {
    id: "banana-yard",
    src: "/photos/banana-yard-960.jpg",
    avif: "/photos/banana-yard-480.avif 480w, /photos/banana-yard-960.avif 960w",
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoUAA0APxl0slCspqSisAgBkCMJYgCdMoABri24AdqPcoOzAAD+F1lASb3GCD1M+723s8pBqiKVOtgqD6fvwuiqJ3LhhhLkCZg5h9JglARqnQm9ck/Li9AM1BX5MpuiBbf4AAAA",
    width: 960, height: 600,
    alt: {"en":"Banana growing right up to the wall of the house","hi":"घर की दीवार तक उगे केले","mr":"घराच्या भिंतीपर्यंत वाढलेली केळी"},
    where: {"en":"India","hi":"भारत","mr":"भारत"},
    author: "Kabang Bladina Gideon",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:A_banana_plantation.jpg",
  },
};

/** Which photographs illustrate which farm, region and package. */
export const PHOTO_SETS = {
  regions: {
    "kokan": [
      "aare-ware",
      "mhapan-coast",
      "konkan-coconut"
    ],
    "nashik": [
      "sula-vineyard",
      "bhavli-igatpuri",
      "koroli-valley"
    ]
  },
  farms: {
    "amrai-wadi-pawas": [
      "mango-laterite",
      "pabhare-house",
      "aare-ware"
    ],
    "kaju-mala-achara": [
      "mhapan-coast",
      "vengurla-cashew",
      "vengurla-road"
    ],
    "bhat-shet-roha": [
      "rice-terraces",
      "palm-paddy",
      "green-lush"
    ],
    "warli-angan-jawhar": [
      "jawhar-falls",
      "zarye-mist",
      "chandgad-hills"
    ],
    "supari-bagayat-guhagar": [
      "konkan-coconut",
      "palm-paddy",
      "hedvi-sunset"
    ],
    "kokam-aali-kudal": [
      "mango-laterite-2",
      "vengurla-road",
      "zarye-mist"
    ],
    "draksha-mala-ozar": [
      "sula-vineyard",
      "sula-estate",
      "koroli-valley"
    ],
    "igatpuri-dhara-ghoti": [
      "bhavli-igatpuri",
      "green-lush",
      "chandgad-hills"
    ],
    "dalimb-bagh-rahuri": [
      "targaon-farmland",
      "sugarcane-village",
      "koroli-valley"
    ],
    "kelibaug-raver": [
      "banana-grove",
      "banana-yard",
      "sugarcane-village"
    ],
    "satpuda-padar-toranmal": [
      "satpura-lohara",
      "koroli-valley",
      "targaon-farmland"
    ],
    "kanda-ghar-lasalgaon": [
      "onion-harvest",
      "targaon-farmland",
      "paddy-harvest"
    ]
  },
  packages: {
    "kokan-mango-weekend": [
      "mango-laterite"
    ],
    "kokan-creek-and-cashew": [
      "mhapan-coast"
    ],
    "nashik-vineyard-two-days": [
      "sula-vineyard"
    ],
    "nashik-monsoon-climb": [
      "bhavli-igatpuri"
    ]
  },
} as const;

/** The stills the front-page reel drifts across, in order. */
export const REEL: readonly string[] = ["hedvi-sunset","aare-ware","rice-terraces","pabhare-house","zarye-mist","mhapan-coast"];

export function photosFor(kind: 'regions' | 'farms' | 'packages', slug: string): Photo[] {
  const ids = (PHOTO_SETS[kind] as Record<string, readonly string[]>)[slug] ?? [];
  return ids.map((id) => PHOTOS[id]).filter(Boolean);
}
