/* Generated by scripts/build-reel.mjs — do not edit by hand. */

/** The photographs the front-page reel drifts across, in the order it shows them. */
export const REEL_FRAMES: readonly string[] = ["hedvi-sunset","aare-ware","rice-terraces","pabhare-house","zarye-mist","mhapan-coast"];

/** Inlined 24px still, painted under the poster so the hero is never empty. */
export const REEL_BLUR = "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoYAA4APxF0slCsJqSisAgBgCIJQBOgA9C3OHh9mUggAPHTPughCPxdm98F06fdrPnbDMfP0f9sgrCiC4+T+dbs5KPNLRxDZYXDi6WH2pLA8XsAAAA=";

/** Seconds. Used to decide when the loop can be released from memory. */
export const REEL_SECONDS = 26.6;
